# Generated by Django 2.1.7 on 2019-03-18 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=6)),
                ('salt', models.CharField(max_length=10)),
                ('api_key_hash', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_id'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['token'], name='devices_dev_token_499d32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'name'), ('user', 'sequence_id')},
        ),
    ]
