# Generated by Django 2.1.7 on 2019-03-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_collected', models.DateTimeField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_measurement_set', to='devices.Device')),
            ],
            options={
                'ordering': ['-date_collected'],
            },
        ),
        migrations.AddIndex(
            model_name='gpsmeasurement',
            index=models.Index(fields=['date_collected'], name='measurement_date_co_7124ea_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsmeasurement',
            index=models.Index(fields=['device', 'date_collected'], name='measurement_device__acb090_idx'),
        ),
    ]
